# Generated by Django 3.2.5 on 2021-07-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_hash", models.CharField(max_length=128)),
                ("contract_id", models.CharField(max_length=128)),
                ("owner_account_id", models.CharField(max_length=128)),
                ("updated_at", models.CharField(max_length=128)),
                ("file_name", models.CharField(max_length=128)),
                ("file_size", models.CharField(max_length=128)),
                ("cid", models.CharField(max_length=128))
            ],
            options={
                "abstract": False,
            },
        ),
    ]
