# Generated by Django 3.2.5 on 2022-05-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='cid',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='contract_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner_account_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_at',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
