# Generated by Django 3.2.5 on 2022-05-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(db_index=True, max_length=255)),
                ('account_id', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
